services:
  mongo:
    image: mongo:7
    container_name: cafetal-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: cafetal-api
      ports:
        - "3000:3000"
      env_file:
        - .env
      environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/cafetal-sobre-piedra?authSource=admin
      depends_on:
        - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cafetal-frontend
    ports:
      - "8080:80"
    depends_on:
      - api    

volumes:
  mongo-data:            