name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Angular app
        working-directory: ./frontend
        run: npx ng build --base-href /Cafetal-sobre-piedra/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Para Angular 17+, la ruta suele ser dist/<nombre-proyecto>/browser
          # Si usas Angular 16 o inferior, cambia la ruta a './frontend/dist/cafetal-sobre-piedra'
          path: './frontend/dist/cafetal-sobre-piedra/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
